using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;     /// для streamreader, streamwriter
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Forms;
using System.Collections.ObjectModel; /// <Необходимо для observable Collection>
///using ;
/// 
/// </summary>


namespace EnglishLearnWPF
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public class Dict
    {
        public string english { get; set; }
        public string russian { get; set; }
        public bool learned { get; set; }
    }




    public partial class MainWindow : Window
    {
        ObservableCollection<Dict> myDict = new ObservableCollection<Dict>();
            //{
            //    new Dict { english = "1", russian = "1", learned = false }
            //};

        private void Logger(string error)
        {
            try
            {
                using (StreamWriter errFile = new StreamWriter("logger.log", true, System.Text.Encoding.Default))
                {
                    errFile.WriteLine(error);
                    errFile.Close();
                }
            }
            catch (Exception e)
            {
                StreamWriter errFile = new StreamWriter("logger.log", false, System.Text.Encoding.Default);
                errFile.WriteLine(e.Message);
                errFile.Close();
            }
            
        }
        
        public MainWindow()
        {
              InitializeComponent();
        }

        public void LoadDict(object sender, RoutedEventArgs e)
        { 
            string FilePath;
            OpenFileDialog openDialog = new OpenFileDialog();
            if (Convert.ToBoolean(openDialog.ShowDialog()) == true)
            {
                FilePath = openDialog.FileName;
                dataGrid.ItemsSource = myDict;
                string tempString = "";
                StreamReader sr = new StreamReader(FilePath);
                tempString = sr.ReadLine();
                if (String.Equals (tempString, "Right File"))
                    {
                    firstform.Title = $"EnglishLearn - {openDialog.FileName}";
                    tempString = sr.ReadLine();
                    while (tempString != null)
                        {
                          string[] arrString = tempString.Split(':');
                          myDict.Add(new Dict { english = arrString[0], russian = arrString[1], learned = Boolean.Parse(arrString[2]) });///
                          tempString = sr.ReadLine();
                          button3.Background = new SolidColorBrush(Colors.Green);
                        }
                    dataGrid.ItemsSource = myDict;
                    sr.Close();
                    }
                else { firstform.Title = "EnglishLearn - WRONG FILE"; };
            }

        }

        public void Button2_Click(object sender, RoutedEventArgs e)
        {

            dataGrid.ItemsSource = myDict;

        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            throw new NotImplementedException();
        }

        private void Button1_Click(object sender, RoutedEventArgs e)

        {

            StreamWriter sr = new StreamWriter("c:/temp/123.txt");
            dataGrid.ItemsSource = myDict;
            foreach (Dict Dict in myDict)
                     sr.WriteLine(Dict.english+":"+Dict.russian+":"+Dict.learned);

            sr.Close();
            Hello.Background = new SolidColorBrush(Colors.Red);                ;
        }

        private void printButton_Click(object sender, RoutedEventArgs e)
        {
            Logger("test");
            System.Windows.Controls.PrintDialog printDialog = new System.Windows.Controls.PrintDialog();
            if (printDialog.ShowDialog() == true)
            {
                printDialog.PrintVisual(dataGrid, "moi file");
            }
        }

        private void Variant_button_Click(object sender, RoutedEventArgs e)
        {
            if (Variant_button.Content == "Переводим на английский")
                {
                Variant_button.Content = "Переводим на русский";
                }
            else
            {
                Variant_button.Content = "Переводим на английский";
            }
        }

        private void textBox_PreviewTextInput(object sender, TextCompositionEventArgs e) // проверка ввода цифры
        {
            int val;
            if ((!Int32.TryParse(e.Text, out val)))  //|| (e.Text==null)
            {
                e.Handled = true;
            }
        }

        private void textBox_TextInput(object sender, TextCompositionEventArgs e)
        {

        }

        private void textBox_TextChanged(object sender, TextChangedEventArgs e)   // проверка попадания в интервал
        {
            int val;
            if (Int32.TryParse(textBox.Text, out val))
            {
                if ((Int32.Parse(textBox.Text) < 1) | (Int32.Parse(textBox.Text) > 50))
                {
                    textBox.Text = "50";
                }
            }
            //char [] s = textBox.Text.ToCharArray();
            //label.Content = s[0];
           
        }
    }
}
